# -*- coding: utf-8 -*-
"""Deliverable_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16N47s8XQuCWFDTq_TltqXpwZ_UjbYo3f
"""

# Step(1): Importing Libraries 
import pandas as pd
import numpy as np
import seaborn as sns

# Step(2): Loading iris dataset
iris = sns.load_dataset('iris')
iris.head()

#Step(3): Dropping the "species" colum
iris = iris.drop(labels = 'species',axis = 1, inplace = True)
iris.head()

#Step(4): Adding columns
iris['sepal_sum'] = iris['sepal_length'] + iris['sepal_width']
iris.head()

#Step(5)
mean = [np.mean(iris['sepal_length']),
        np.mean(iris['sepal_width']),
        np.mean(iris['sepal_sum']),
        np.mean(iris['petal_length']),
        np.mean(iris['petal_width'])]
       

summary_dict = {'mean':mean}

summary_df = pd.DataFrame(data = summary_dict)

summary_df

iris.mean()

iris.std()

iris.describe()